--IMP
SELECT  DISTINCT
        CC.GKEY GKEY_SCRIPT,
        BL.NBR BL,
        UNIT.ID UNIT,
        CC.CUSTOMREGCON_CONTENTTYPE TIPO,
        CC.CUSTOMREGCON_REGISTRYGKEY REGISTRO_AVERBACAO
FROM
        SPARCSN4PRD.CRG_BILLS_OF_LADING BL
        ,SPARCSN4PRD.CUSTOM_REGISTRY CR
        ,SPARCSN4PRD.CUSTOM_CUSTOMREGISTRYCONTENT CC
        ,SPARCSN4PRD.inv_unit UNIT

WHERE
        BL.GKEY = CR.CUSTOMREGIST_BILLOFLADIN
        AND BL.GKEY = CC.CUSTOMREGCON_ENTITYID_L
        AND CC.CUSTOMREGCON_CONTENTID_L = UNIT.GKEY
        AND (CC.CUSTOMREGCON_REGISTRYGKEY = CR.GKEY OR CC.CUSTOMREGCON_REGISTRYGKEY IS NULL)
        
        AND BL.NBR = 'EXP19010018'
;

SELECT min(CUSTOMSCTRAN_REGISTRY) FROM SPARCSN4PRD.CUSTOM_SCHEDULETRANSIT CS WHERE customsctran_custombooking = 34243212
;

select cs.gkey GKEY_TAB,cs.CUSTOMSCTRAN_UNITID UNIT, cs.customsctran_registry REGISTRO, 
cs.CUSTOMSCTRAN_CUSTOMDOCUMENTS DOC, cs.CUSTOMSCTRAN_CUSTOMSTATUSDOC STATUS 
from    sparcsn4prd.custom_scheduletransit cs
where customsctran_custombooking = 34243212
order by CUSTOMSCTRAN_UNITID;


SELECT CUSTOMSCTRAN_REGISTRY, CS.* FROM SPARCSN4PRD.CUSTOM_SCHEDULETRANSIT CS WHERE CUSTOMSCTRAN_CUSTOMSTATUSDOC is null;

