-- CUE ARCHIVE
SELECT  CUEAR.LAST_DRAFT_INV_NBR,
        'sbRetorno.append(unPurge("'||CUEAR.LAST_DRAFT_INV_NBR||'"));' AS SCRIPT
        ,CUEAR.GKEY ,CUEAR.EVENT_TYPE, CUEAR.STATUS, CUEAR.EQUIPMENT_ID ,CUEAR.BL_NBR AS BL, CUEAR.BOOKING_NBR AS BOOKING
FROM    SPARCSN4PRD.ARGO_AR_CHARGEABLE_UNIT_EVENTS CUEAR
WHERE   CUEAR.BL_NBR 
IN      ('BSZEA1805033',
'BNBFL18040379',
'BQDEA1808060',
'BSZEA1711076',
'NBFC1711068',
'BNBFL18060646')
ORDER BY CUEAR.LAST_DRAFT_INV_NBR, CUEAR.GKEY
;
--------------------------------------------------------------------------------------------------------------------------------
SELECT  'atualizarEventGkey(' AS SCRIPT1,
        NULL AS SCRIPT2,
        '); //' || EVENT_TYPE_ID || ' - ' || EVENT_ID AS SCRIPT3
        ,INV.DRAFT_NBR ,INV.STATUS     
        ,INVIT.GKEY ,INVIT.EXTRACT_GKEY, INVIT.EVENT_TYPE_ID, INVIT.DESCRIPTION ,INVIT.EVENT_ID
FROM    
        SPARCSN4PRD.BIL_INVOICES            INV 
        ,SPARCSN4PRD.BIL_INVOICE_ITEMS      INVIT
WHERE   
        INVIT.INVOICE_GKEY = inv.gkey
        AND INV.DRAFT_NBR IN (393335,393948,393996,399427,432170,442586,452412)
ORDER BY INV.DRAFT_NBR
;
